### PR TITLE
Add empty headers to HTML tables without headers when converted to markdown

### PR DESCRIPTION
**Pull request by NikolasKomonen**
This is necessary because Markdown will not render a table without a header defined.

Related issue here: https://github.com/giflw/remark-java/issues/9

Here is an example of the markdown not rendering without the empty table header.

markdownTable

### CODE REVIEW

**Comment by kotcrab** [comment]
Looks okay. Can you format the source code so it matches original files? 
Also you can undo the changes on `MultiMarkdownTest.java`, only the formatting was changed. Generally we want to avoid changes like this because it adds unnecessary noise to git history.

**Comment by NikolasKomonen** [comment]
@kotcrab Sorry I forgot to revert the MultiMarkdownTest changes. Everything should be fixed up. Let me know if there's anything else that needs a change.

**Comment by kotcrab** [comment]
Alright, I see what's wrong. The indentation on your changes is off. This project is unfortunate enough to be using tabs and your changes are using spaces. It may look fine on your end but on Github it's clearly different, you can see it after going to "Files changed" tab.

**Comment by NikolasKomonen** [comment]
@kotcrab Yup, found the indentation issues. Everything should be good now.

**Comment by kotcrab** [comment]
Looks good now, thanks! I'm going to upload v1.1.0 soon.

**Comment by NikolasKomonen** [comment]
@kotcrab Great to see the change up on the maven repo. Thanks a lot for the help!

**Pull request merged**
